### ISSUE TITLE
NeuronChatDB columns: extra genes used in comm strength ?

### ISSUE THREAD

**Issue by Cheyujlee** [Wei-BioMath/NeuronChat#12]
Hi,

Thank you for creating this neural-specific database. I have a question on some of the columns in the neuronchatDB. Specifically:
* targets_up, 
* targets_down, 
* activator, 
* inhibitor, 
* interactions

There seem to be extra genes compared to the lig_contributor,	receptor_subunit. What do they mean and how do they contribute to communication strength? Thanks!
![image](https://github.com/Wei-BioMath/NeuronChat/assets/70779123/c28a9854-aef1-4b5b-8dd5-6c1fa0aa9fa9)

**Comment by Wei-BioMath** [comment]
Hi @Cheyujlee,  sorry for the confusion. You can ignore these terms (which are related to intracellular signaling and designed for facillating intercellular communication prediction ) because they are not included in the published NeuronChat model. These terms were generated when I was developing the package, and are deprecated in the published version.

**Comment by Cheyujlee** [comment]
Thanks!
